# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Specs

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
      env: # Or as an environment variable
        FIRE_ACCESS: ${{ secrets.FIRE_ACCESS }}
    - run: 'echo "FIRE_ACCESS" > firestore.key.json'
    - run: npm install -g yarn
    - run: yarn install
    - run: npx lerna bootstrap
    - run: npx jest
